services:
  db:
    image: "percona/percona-server:8"
    environment:
     - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
	app:
	  image: nginx:1.12
	  volumes:
        - .:/usr/share/nginx/html
      expose:
        - "80"
	app2:
    depends_on:
      - app1
	  image: nginx:1.12
	  volumes:
        - index1.html:/usr/share/nginx/html/index.html
      expose:
        - "80"
	proxy:
      depends_on:
        - app2
      build: ./
      networks:
        - site1
        - site2
      ports:
      - 80:80